# Locations
source: .
destination: ./_site
collections_dir: .
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

sass:
  sass_dir: _sass
collections:
  posts:
    output: true

# Site Attributes
title: "Jekyll Website Template"
tagline: "A template for a simple website"
description: "A template for a simple website running Jekyll, for deployment on GitHub Pages"
layout: default
theme: jekyll-theme-midnight
repository: Umbra-Aeterna-Labs/jekyll-website-template
github: [ metadata ]

# Handling Reading
safe: false
include: [ ".htaccess" ]
exclude: [ "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/" ]
keep_files: [ ".git", ".svn" ]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: false
limit_posts: 0
future: false
unpublished: false

# Plugins
whitelist: [ ]
plugins:
  - jekyll-seo-tag

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false
livereload: FALSE

# Outputting
permalink: date
paginate_path: /page:num
timezone: "America/New_York"
page_excerpts: true
quiet: false
verbose: false
defaults: [ ]

liquid:
  strict_filters: false
  strict_variables: false

# Markdown Processors
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: "1,2,3,4,5,6"
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false